var default = Handlebars.template({"1":function(depth0,helpers,partials,data) {
  var lambda=this.lambda, escapeExpression=this.escapeExpression;
  return "            \""
    + escapeExpression(lambda(depth0, depth0))
    + "\",\r\n";
},"3":function(depth0,helpers,partials,data) {
  var stack1, lambda=this.lambda, escapeExpression=this.escapeExpression, helperMissing=helpers.helperMissing;
  return "                        <li class=\"divider\">Привет, <b>"
    + escapeExpression(lambda(((stack1 = ((stack1 = (depth0 != null ? depth0.user : depth0)) != null ? stack1.name : stack1)) != null ? stack1.first : stack1), depth0))
    + " "
    + escapeExpression(lambda(((stack1 = ((stack1 = (depth0 != null ? depth0.user : depth0)) != null ? stack1.name : stack1)) != null ? stack1.last : stack1), depth0))
    + "</b>!</li>\r\n                        <li><a href=\""
    + escapeExpression(((helpers.profileUrl || (depth0 && depth0.profileUrl) || helperMissing).call(depth0, ((stack1 = (depth0 != null ? depth0.user : depth0)) != null ? stack1._id : stack1), {"name":"profileUrl","hash":{},"data":data})))
    + "\"><span class=\"icon-user\"></span> <span class=\"non-shrink\">Профиль</span></a></li>\r\n";
},"5":function(depth0,helpers,partials,data) {
  return "                        <li class=\"divider\">Привет, регистрируйся!</li>\r\n                        <li><a href=\"/keystone/signin\"><span class=\"icon-user\"></span> <span class=\"non-shrink\">Вход</span></a></li>\r\n";
  },"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var stack1, helper, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression, buffer = "﻿<!doctype html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <title>Markup Main Page</title>\r\n    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,400,600,300&subset=latin,cyrillic' rel='stylesheet' type='text/css'>\r\n    <link rel=\"stylesheet\" href=\"/styles/site.min.css\" />\r\n    <script>\r\n        var chatUserToken = \""
    + escapeExpression(((helper = (helper = helpers.chatUserToken || (depth0 != null ? depth0.chatUserToken : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"chatUserToken","hash":{},"data":data}) : helper)))
    + "\";\r\n        var pageTags = [\r\n";
  stack1 = helpers.each.call(depth0, (depth0 != null ? depth0.pageTags : depth0), {"name":"each","hash":{},"fn":this.program(1, data),"inverse":this.noop,"data":data});
  if (stack1 != null) { buffer += stack1; }
  buffer += "        ];\r\n    </script>\r\n</head>\r\n<body>\r\n    <div class=\"layout app fluid vertical stretch\">\r\n        <main class=\"flex layout horizontal\">\r\n            <aside class=\"layout vertical stretch\">\r\n                <div class=\"logo logo-tiny\">\r\n                    <img src=\"/images/logo-tiny.png\" alt=\"\" />\r\n                </div>\r\n                <div class=\"logo logo-mega\">\r\n                    <img src=\"/images/logo.png\" alt=\"\" />\r\n                </div>\r\n                <nav class=\"flex layout horizontal stretch\">\r\n                    <ul class=\"flex layout vertical stretch\">\r\n                        <li class=\"live\">\r\n                            <a href=\"/streams/live\">\r\n                                <span class=\"icon-microphone\"></span> <span class=\"non-shrink\">Live Now</span>\r\n                            </a>\r\n                        </li>\r\n                        <li class=\"divider\">Бессвязный девелоп</li>\r\n                        <li><a href=\"/streams\"><span class=\"icon-play\"></span> <span class=\"non-shrink\">Стримы</span></a></li>\r\n                        <li><a href=\"#\"><span class=\"icon-folder\"></span> <span class=\"non-shrink\">Проекты</span></a></li>\r\n                        <li><a href=\"#\"><span class=\"icon-heart\"></span> <span class=\"non-shrink\">Люди</span></a></li>\r\n                        <li><a href=\"#\"><span class=\"icon-book\"></span> <span class=\"non-shrink\">Блог</span></a></li>\r\n                    </ul>\r\n                </nav>\r\n                <nav class=\"layout horizontal center profile\">\r\n                    <ul class=\"flex layout vertical stretch\">\r\n";
  stack1 = helpers['if'].call(depth0, (depth0 != null ? depth0.user : depth0), {"name":"if","hash":{},"fn":this.program(3, data),"inverse":this.program(5, data),"data":data});
  if (stack1 != null) { buffer += stack1; }
  buffer += "                    </ul>\r\n                </nav>\r\n            </aside>\r\n            <div id=\"content\" class=\"flex layout vertical scroll\">\r\n                <div class=\""
    + escapeExpression(((helper = (helper = helpers.pageclass || (depth0 != null ? depth0.pageclass : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"pageclass","hash":{},"data":data}) : helper)))
    + " layout horizontal flex stretch\">\r\n                    ";
  stack1 = ((helper = (helper = helpers.body || (depth0 != null ? depth0.body : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"body","hash":{},"data":data}) : helper));
  if (stack1 != null) { buffer += stack1; }
  return buffer + "\r\n                </div>\r\n            </div>\r\n            <div id=\"chat-panel\" class=\"layout vertical chat-panel\">\r\n                <div class=\"scroll\">\r\n                    <div class=\"chat-panel__list layout vertical\">\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </main>\r\n        <footer class=\"footer\">\r\n            <div class=\"chat layout horizontal center\">\r\n                <div class=\"chat__accent\">ЧАТ:</div>\r\n                <div class=\"chat__input flex\">\r\n                    <input id=\"chat\" class=\"chat__input_field\" type=\"text\" />\r\n                </div>\r\n                <button class=\"chat__button\">\r\n                    <span class=\"icon-speech-bubble\"></span>\r\n                </button>\r\n            </div>\r\n        </footer>\r\n    </div>\r\n    <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\r\n    <!-- <script src=\"//cdnjs.cloudflare.com/ajax/libs/flexie/1.0.3/flexie.min.js\"></script> -->\r\n    <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.0/isotope.pkgd.min.js\"></script>\r\n    <script src=\"//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.5/socket.io.min.js\"></script>\r\n    <script src=\"/vendor/jquery.nanoscroller.min.js\"></script>\r\n    <script type=\"text/javascript\" src=\"/js/script.min.js\"></script>\r\n    <link rel=\"stylesheet\" href=\"/icons/style.css\" />\r\n    <link rel=\"stylesheet\" href=\"http://css-spinners.com/css/spinner/whirly.css\" type=\"text/css\">\r\n</body>\r\n</html>\r\n";
},"useData":true});